# Generated by Django 5.2.18 on 2026-10-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Allotment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_date", models.DateField()),
                (
                    "to_date",
                    models.DateField(help_text="Same as 'from' for a single day"),
                ),
                ("reason", models.CharField(max_length=150)),
            ],
            options={
                "ordering": ["-from_date"],
            },
        ),
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Short name, e.g. CSE-2-A", max_length=100
                    ),
                ),
                ("branch", models.CharField(help_text="e.g. CSE", max_length=60)),
                (
                    "year",
                    models.PositiveSmallIntegerField(help_text="Year of study, e.g. 2"),
                ),
                (
                    "semester",
                    models.PositiveSmallIntegerField(help_text="Semester, e.g. 1"),
                ),
                ("section", models.CharField(help_text="e.g. A", max_length=10)),
            ],
            options={
                "verbose_name_plural": "classes",
                "ordering": ["branch", "year", "semester", "section"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_no", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120)),
            ],
            options={
                "ordering": ["roll_no"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(max_length=30)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
