# Generated by Django 5.2.18 on 2026-10-08 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="allotment",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allotments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolclass",
            constraint=models.UniqueConstraint(
                fields=("branch", "year", "semester", "section"),
                name="unique_class_identity",
            ),
        ),
        migrations.AddField(
            model_name="holiday",
            name="school_class",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank for the whole college",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holidays",
                to="academics.schoolclass",
                verbose_name="Only for class",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="school_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="academics.schoolclass",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="school_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="academics.schoolclass",
            ),
        ),
        migrations.AddField(
            model_name="allotment",
            name="subject",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allotment",
                to="academics.subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("school_class", "code"), name="unique_subject_code_per_class"
            ),
        ),
    ]
